-- Add MPC (Minor Planet Center) columns to small_bodies table

ALTER TABLE small_bodies
ADD COLUMN IF NOT EXISTS MPC_DESIGNATION VARCHAR(15) COMMENT 'MPC designation',
ADD COLUMN IF NOT EXISTS MPC_H FLOAT COMMENT 'Absolute magnitude (MPC)',
ADD COLUMN IF NOT EXISTS MPC_G FLOAT COMMENT 'Slope parameter',
ADD COLUMN IF NOT EXISTS MPC_EPOCH VARCHAR(10) COMMENT 'Epoch (packed form)',
ADD COLUMN IF NOT EXISTS MPC_M FLOAT COMMENT 'Mean anomaly (degrees)',
ADD COLUMN IF NOT EXISTS MPC_PERI FLOAT COMMENT 'Argument of perihelion (degrees)',
ADD COLUMN IF NOT EXISTS MPC_NODE FLOAT COMMENT 'Longitude of ascending node (degrees)',
ADD COLUMN IF NOT EXISTS MPC_INCL FLOAT COMMENT 'Inclination (degrees)',
ADD COLUMN IF NOT EXISTS MPC_E FLOAT COMMENT 'Eccentricity',
ADD COLUMN IF NOT EXISTS MPC_N FLOAT COMMENT 'Mean daily motion (degrees/day)',
ADD COLUMN IF NOT EXISTS MPC_A FLOAT COMMENT 'Semi-major axis (AU)',
ADD COLUMN IF NOT EXISTS MPC_REFERENCE VARCHAR(20) COMMENT 'Reference',
ADD COLUMN IF NOT EXISTS MPC_NUM_OBS INT COMMENT 'Number of observations',
ADD COLUMN IF NOT EXISTS MPC_NUM_OPP INT COMMENT 'Number of oppositions',
ADD COLUMN IF NOT EXISTS MPC_ARC VARCHAR(20) COMMENT 'Arc of observations',
ADD COLUMN IF NOT EXISTS MPC_RMS FLOAT COMMENT 'RMS residual',
ADD COLUMN IF NOT EXISTS MPC_PERTURBERS VARCHAR(10) COMMENT 'Perturbers',
ADD COLUMN IF NOT EXISTS MPC_COMPUTER VARCHAR(20) COMMENT 'Computer name',
ADD COLUMN IF NOT EXISTS MPC_FLAGS VARCHAR(10) COMMENT '4-digit flags',
ADD COLUMN IF NOT EXISTS MPC_NAME VARCHAR(50) COMMENT 'Readable name',
ADD COLUMN IF NOT EXISTS MPC_LAST_UPDATED DATETIME COMMENT 'Last update from MPC',

ADD INDEX IF NOT EXISTS idx_mpc_designation (MPC_DESIGNATION),
ADD INDEX IF NOT EXISTS idx_mpc_a (MPC_A);

